<a href="https://colab.research.google.com/github/Paolo20224/Prueba/blob/main/Desaf%C3%ADo_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
#Como parte inicial, descargamos la informacion y la cargamos en nuestro cuader en Colab
import pandas as pd
filename = "/content/abalone.data"
df = pd.read_csv(filename)

1.Analisis y Depuracion de Datos

In [49]:
#A continuacion revisaremos los primeros datos, donde vemos que no vienen incluidos los nombres de las columnas, y la primera fila son datos
df.head(5)

M  0.455  0.365  0.095   0.514  0.2245   0.101   0.15  15
0  M  0.350  0.265  0.090  0.2255  0.0995  0.0485  0.070   7
1  F  0.530  0.420  0.135  0.6770  0.2565  0.1415  0.210   9
2  M  0.440  0.365  0.125  0.5160  0.2155  0.1140  0.155  10
3  I  0.330  0.255  0.080  0.2050  0.0895  0.0395  0.055   7
4  I  0.425  0.300  0.095  0.3515  0.1410  0.0775  0.120   8

In [50]:
# A continuacion agregaremos el nombre de las columnas respectivamente y agregaremos los datos de la fila 0 que se perdieron al incorporar el nombre de las columnas
df2=df
df2.columns = ['Sex',
              'Length',
              'Diameter',
              'Height',
              'Whole_weight',
              'Shucked_weight',
              'Viscera_weight',
              'Shell_weight',
              'Rings']

nueva_fila = {'Sex':'M', 'Length':0.455, 'Diameter':0.365, 'Height':0.095, 'Whole_weight':0.514, 'Shucked_weight':0.2245, 'Viscera_weight':0.101, 'Shell_weight':0.15, 'Rings':15}
df2 = df2.append(nueva_fila, ignore_index=True)

In [51]:
# A continuacion revisaremos la categoria de cada dato, asi como tambien su integridad (verificacion de nulos)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4177 entries, 0 to 4176
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Sex             4177 non-null   object 
 1   Length          4177 non-null   float64
 2   Diameter        4177 non-null   float64
 3   Height          4177 non-null   float64
 4   Whole_weight    4177 non-null   float64
 5   Shucked_weight  4177 non-null   float64
 6   Viscera_weight  4177 non-null   float64
 7   Shell_weight    4177 non-null   float64
 8   Rings           4177 non-null   int64  
dtypes: float64(7), int64(1), object(1)
memory usage: 293.8+ KB


In [52]:
#A continuacion revisaremos la estadistica descriptiva
df2.describe()

Length     Diameter       Height  Whole_weight  Shucked_weight  \
count  4177.000000  4177.000000  4177.000000   4177.000000     4177.000000   
mean      0.523992     0.407881     0.139516      0.828742        0.359367   
std       0.120093     0.099240     0.041827      0.490389        0.221963   
min       0.075000     0.055000     0.000000      0.002000        0.001000   
25%       0.450000     0.350000     0.115000      0.441500        0.186000   
50%       0.545000     0.425000     0.140000      0.799500        0.336000   
75%       0.615000     0.480000     0.165000      1.153000        0.502000   
max       0.815000     0.650000     1.130000      2.825500        1.488000   

       Viscera_weight  Shell_weight        Rings  
count     4177.000000   4177.000000  4177.000000  
mean         0.180594      0.238831     9.933684  
std          0.109614      0.139203     3.224169  
min          0.000500      0.001500     1.000000  
25%          0.093500      0.130000     8.000000  
50%          0.171000      0.234000     9.000000  
75%          0.253000      0.329000    11.000000  
max          0.760000      1.005000    29.000000

In [53]:
#A continuacion analizamos la correlacion entra las variables cuantitativas.

import pandas as pd

corr_df2 = df2.corr(method='pearson')

corr_df2.style.background_gradient(cmap='coolwarm')

1. Creacion y Optimizacion de Modelo Predictivo

In [54]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import matplotlib.patches as mpatches
import seaborn as sb

%matplotlib inline
plt.rcParams['figure.figsize'] = (16, 9)
plt.style.use('ggplot')

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

Preparamos el dataset

In [55]:
X1 = df2[['Length','Diameter','Height','Whole_weight','Whole_weight','Viscera_weight','Shell_weight']].values
y1 = df2['Rings'].values

X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1,test_size=0.3, random_state=123)
scaler = MinMaxScaler()
X_train1 = scaler.fit_transform(X_train1)
X_test1 = scaler.transform(X_test1)

Creamos el Modelo


In [56]:
#Realizamos iteraciones para "N° de vecinos" y nos quedamos con el mejor equilibrio para el nivel de precision de test y entrenamiento.

n_neighbors = 50

knn = KNeighborsClassifier(n_neighbors)
knn.fit(X_train1, y_train1)
print('Accuracy of K-NN classifier on training set: {:.2f}'
     .format(knn.score(X_train1, y_train1)))
print('Accuracy of K-NN classifier on test set: {:.2f}'
     .format(knn.score(X_test1, y_test1)))

Accuracy of K-NN classifier on training set: 0.30
Accuracy of K-NN classifier on test set: 0.28


Resultados obtenidos

In [57]:
pred = knn.predict(X_test1)
print(confusion_matrix(y_test1, pred))
print(classification_report(y_test1, pred))

[[ 0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  3  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 10  8  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1 16 14  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 12 23 29  8  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  7 21 45 26 11  5  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 14 30 63 43 15  3  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  3 21 39 86 59 11  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  5 15 27 47 76 23  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  2 15 34 59 28  1  2  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  9 19 31 14  2  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  6  6 11 20 14  1  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  7  6  8  7  4  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  3  8 12 10  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  6  5  7  4  0

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Preparamos el dataset

In [58]:
X2 = df2[['Length','Diameter','Height','Whole_weight','Whole_weight','Viscera_weight','Shell_weight','Rings']].values
y2 = df2['Sex'].values

X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2,test_size=0.3, random_state=123)
scaler = MinMaxScaler()
X_train2 = scaler.fit_transform(X_train2)
X_test2 = scaler.transform(X_test2)

Creamos el Modelo

In [59]:
n_neighbors = 50

knn = KNeighborsClassifier(n_neighbors)
knn.fit(X_train2, y_train2)
print('Accuracy of K-NN classifier on training set: {:.2f}'
     .format(knn.score(X_train2, y_train2)))
print('Accuracy of K-NN classifier on test set: {:.2f}'
     .format(knn.score(X_test2, y_test2)))

Accuracy of K-NN classifier on training set: 0.59
Accuracy of K-NN classifier on test set: 0.54


Resultados obtenidos

In [60]:
pred = knn.predict(X_test2)
print(confusion_matrix(y_test2, pred))
print(classification_report(y_test2, pred))

[[142  60 182]
 [ 38 317  53]
 [150  96 216]]
              precision    recall  f1-score   support

           F       0.43      0.37      0.40       384
           I       0.67      0.78      0.72       408
           M       0.48      0.47      0.47       462

    accuracy                           0.54      1254
   macro avg       0.53      0.54      0.53      1254
weighted avg       0.53      0.54      0.53      1254



2. Preguntas y Respuestas:



*   ¿Podrías haber utilizado la regresión lineal y la regresión KNN para resolver el problema de regresión?

R: El problema presentaba altos niveles de correlacion entre las variables cuantitativas, sin embargo no permitia llegar a mayores niveles de prediccion dentro del modelo.

*   ¿Podrías haber utilizado la regresión lineal para el problema de clasificación?

R: Es posible, sin embargo no se llegan a niveles de precision y prediccionar dentro de un margen esperado.




# **Ejercicio de división entrenar probar**

A) Regresion Linear Sin entrenamiento

In [61]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris
from sklearn.metrics import precision_recall_fscore_support
from sklearn.neighbors import KNeighborsRegressor

In [62]:
reg = LinearRegression(fit_intercept=True)
reg.fit(X1,y1)
score = reg.score(X1, y1)
print(score)

0.4593293877921072


B) KNN Sin Entrenamiento

In [63]:
X1 = df2[['Length','Diameter','Height','Whole_weight','Whole_weight','Viscera_weight','Shell_weight']].values
y1 = df2['Rings'].values
n_neighbors = 50

knn = KNeighborsClassifier(n_neighbors)
knn.fit(X1, y1)
print('Accuracy of K-NN classifier on set: {:.2f}'
     .format(knn.score(X1, y1)))

Accuracy of K-NN classifier on set: 0.30


C) Regresion Linear Con entrenamiento

In [64]:
reg = LinearRegression(fit_intercept=True)
reg.fit(X_test1,y_test1)
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1,test_size=0.3, random_state=123)
scaler = MinMaxScaler()
X_train1 = scaler.fit_transform(X_train1)
X_test1 = scaler.transform(X_test1)

score = reg.score(X_test1, y_test1)
print(score)

0.4419676394699392


D) KNN Con Entrenamiento

In [65]:
X1 = df2[['Length','Diameter','Height','Whole_weight','Whole_weight','Viscera_weight','Shell_weight']].values
y1 = df2['Rings'].values

X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1,test_size=0.3, random_state=123)
scaler = MinMaxScaler()
X_train1 = scaler.fit_transform(X_train1)
X_test1 = scaler.transform(X_test1)

n_neighbors = 50

knn = KNeighborsClassifier(n_neighbors)
knn.fit(X_train1, y_train1)
print('Accuracy of K-NN classifier on training set: {:.2f}'
     .format(knn.score(X_train1, y_train1)))
print('Accuracy of K-NN classifier on test set: {:.2f}'
     .format(knn.score(X_test1, y_test1)))

Accuracy of K-NN classifier on training set: 0.30
Accuracy of K-NN classifier on test set: 0.28


# **Preguntas & Respuestas del Ejercicio**

1.¿Cuál de KNN o regresión lineal pareció un mejor modelo cuando no usaste la división entrenar probar?

R: Regresion lineal mostro un mejor nivel de prediccion vs KNN

2.¿Cuál de KNN o regresión lineal pareció un mejor modelo cuando usaste la 
división entrenar probar?

R: Regresion lineal, siguio mostrando un mejor rendimiento

3.¿Hubo alguna ventaja en la regresión lineal en términos de la cantidad de código que tenías que escribir?

R: claramente es un codigo más resumido que KNN

4.¿Hay alguna forma de mostrarle a alguien cuál de los dos modelos fue más efectivo?

R: siempre esta la posibilidad de graficar ambos modelos y comparar cual genera más ruido o residuo, asi como tambien medir los minimos cuadrados de cada modelo.

5¿Crees que podrías haber mejorado KNN para mejorar la eficacia del modelo?

R: intente modificar las proporciones de test y entrenamiento, asi como transformar variables discrecionales en continuas, pero no obtuve una mejora sustancial.