<a href="https://colab.research.google.com/github/Paolo20224/Prueba/blob/main/EEG_machinelearing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
#Como parte inicial, descargamos la informacion y la cargamos en nuestro cuader en Colab
import pandas as pd
filename = "/content/EEG.machinelearing_data_BRMH.csv"
df = pd.read_csv(filename)

1.Analisis y Depuracion de Datos

In [35]:
# A continuacion revisaremos la categoria de cada dato, asi como tambien su integridad (verificacion de nulos)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 945 entries, 0 to 944
Columns: 1149 entries, no. to COH.F.gamma.r.O1.s.O2
dtypes: float64(1144), int64(1), object(4)
memory usage: 8.3+ MB


In [36]:
#A continuacion revisaremos el archivo en excel para validar que elementos conducentes a error puede contener esta base.
df.to_excel("EEGML.xlsx", index=False)

In [42]:
df2=df
df2 = df2.dropna(subset=["education"])
df2 = df2.dropna(subset=["IQ"])

1. Creacion y Optimizacion de Modelo Predictivo

In [43]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import matplotlib.patches as mpatches
import seaborn as sb

%matplotlib inline
plt.rcParams['figure.figsize'] = (16, 9)
plt.style.use('ggplot')

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

Preparamos el dataset

In [87]:
X=df2.drop(columns=['main.disorder','sex','eeg.date','specific.disorder','Unnamed: 122'])
y = df2['main.disorder'].values

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3, random_state=123)
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

Creamos el Modelo

In [100]:
#Realizamos iteraciones para "N° de vecinos" y nos quedamos con el mejor equilibrio para el nivel de precision de test y entrenamiento.

n_neighbors = 90

knn = KNeighborsClassifier(n_neighbors)
knn.fit(X_train, y_train)
print('Accuracy of K-NN classifier on training set: {:.2f}'
     .format(knn.score(X_train, y_train)))
print('Accuracy of K-NN classifier on test set: {:.2f}'
     .format(knn.score(X_test, y_test)))

Accuracy of K-NN classifier on training set: 0.31
Accuracy of K-NN classifier on test set: 0.26


Resultados obtenidos

In [101]:
pred = knn.predict(X_test)
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

[[11  0  0 42  0  0  0]
 [ 3  0  0 32  0  0  0]
 [ 2  0  0 24  0  0  0]
 [ 7  0  0 62  0  0  0]
 [ 0  0  0 14  0  0  0]
 [ 2  0  0 37  0  0  0]
 [ 4  0  0 36  0  0  0]]
                                    precision    recall  f1-score   support

                Addictive disorder       0.38      0.21      0.27        53
                  Anxiety disorder       0.00      0.00      0.00        35
                   Healthy control       0.00      0.00      0.00        26
                     Mood disorder       0.25      0.90      0.39        69
     Obsessive compulsive disorder       0.00      0.00      0.00        14
                     Schizophrenia       0.00      0.00      0.00        39
Trauma and stress related disorder       0.00      0.00      0.00        40

                          accuracy                           0.26       276
                         macro avg       0.09      0.16      0.09       276
                      weighted avg       0.14      0.26      0.15    

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Arbol de Decision

In [102]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
from sklearn import tree
import matplotlib.pyplot as plt

In [103]:
X=df2.drop(columns=['main.disorder','sex','eeg.date','specific.disorder','Unnamed: 122']).values
y=df2['main.disorder'].values

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3, random_state=123)

tree_clf = DecisionTreeClassifier(max_depth=700)
tree_clf.fit(X_train, y_train)
# Visualizando árbol de decisión
# Nueva instancia
# CALCULAMOS LAS Probabilidades por cada clase
print(tree_clf.predict_proba(X_test))
# Clase predicha
pred=tree_clf.predict(X_test)
print("Esta instancia pertenece a la clase",tree_clf.predict(X_test))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]
Esta instancia pertenece a la clase ['Mood disorder' 'Mood disorder' 'Addictive disorder' 'Anxiety disorder'
 'Healthy control' 'Healthy control' 'Anxiety disorder' 'Healthy control'
 'Mood disorder' 'Anxiety disorder' 'Trauma and stress related disorder'
 'Mood disorder' 'Healthy control' 'Mood disorder'
 'Trauma and stress related disorder' 'Mood disorder'
 'Obsessive compulsive disorder' 'Mood disorder' 'Mood disorder'
 'Mood disorder' 'Mood disorder' 'Healthy control' 'Anxiety disorder'
 'Addictive disorder' 'Anxiety disorder' 'Mood disorder' 'Mood disorder'
 'Anxiety disorder' 'Trauma and stress related disorder' 'Healthy control'
 'Addictive disorder' 'Schizophrenia' 'Mood disorder' 'Mood disorder'
 'Addictive disorder' 'Trauma and stress related disorder' 'Mood disorder'
 'Mood disorder' 'Trauma and stress related disorder' '

In [104]:
pred = tree_clf.predict(X_test)
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

[[33  3  4  6  0  3  4]
 [ 2  6  0 19  1  3  4]
 [ 0  0 26  0  0  0  0]
 [ 5  8  0 40  1  8  7]
 [ 1  1  0  6  4  1  1]
 [ 2  9  0 12  3 10  3]
 [ 7  1  0 17  0  7  8]]
                                    precision    recall  f1-score   support

                Addictive disorder       0.66      0.62      0.64        53
                  Anxiety disorder       0.21      0.17      0.19        35
                   Healthy control       0.87      1.00      0.93        26
                     Mood disorder       0.40      0.58      0.47        69
     Obsessive compulsive disorder       0.44      0.29      0.35        14
                     Schizophrenia       0.31      0.26      0.28        39
Trauma and stress related disorder       0.30      0.20      0.24        40

                          accuracy                           0.46       276
                         macro avg       0.46      0.45      0.44       276
                      weighted avg       0.45      0.46      0.45    

Random Forests

In [105]:
from sklearn.ensemble import RandomForestClassifier

rndf_clf = RandomForestClassifier(n_estimators=100)
rndf_clf.fit(X_train, y_train)
y_pred = rndf_clf.predict(X_test)

pred = rndf_clf.predict(X_test)
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

rndf_clf.score(X_test, y_test)

[[26  0  3 22  0  0  2]
 [ 3  0  0 32  0  0  0]
 [10  0  6  9  0  0  1]
 [ 9  0  1 58  0  0  1]
 [ 1  0  0 13  0  0  0]
 [ 3  0  0 33  0  2  1]
 [10  0  0 29  0  0  1]]
                                    precision    recall  f1-score   support

                Addictive disorder       0.42      0.49      0.45        53
                  Anxiety disorder       0.00      0.00      0.00        35
                   Healthy control       0.60      0.23      0.33        26
                     Mood disorder       0.30      0.84      0.44        69
     Obsessive compulsive disorder       0.00      0.00      0.00        14
                     Schizophrenia       1.00      0.05      0.10        39
Trauma and stress related disorder       0.17      0.03      0.04        40

                          accuracy                           0.34       276
                         macro avg       0.35      0.23      0.19       276
                      weighted avg       0.38      0.34      0.25    

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.33695652173913043